# Generated by Django 2.2.6 on 2019-11-12 22:50

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(default='', max_length=1000, verbose_name='片名')),
                ('directors', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='导演')),
                ('editors', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='编剧')),
                ('leadactors', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='主演')),
                ('nation', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='国家')),
                ('language', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='语言')),
                ('releasedate', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='上映年份')),
                ('othername', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='又名')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='简介')),
                ('durations', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='片长')),
                ('numrating', models.IntegerField(blank=True, default=0, null=True, verbose_name='评分人数')),
                ('typelist', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='类型')),
                ('averating', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='评分(0-5)')),
                ('picture', models.CharField(blank=True, default='/static/img/m16.jpg', max_length=1000, null=True, verbose_name='缩略图')),
                # ('backpost', models.CharField(blank=True, default='/static/img/m16.jpg', max_length=3000, null=True, verbose_name='详情页海报')),
            ],
            options={
                'verbose_name': '电影信息',
                'verbose_name_plural': '电影信息',
            },
        ),
        migrations.CreateModel(
            name='MovieSimilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.IntegerField(default=0, verbose_name='电影id')),
                ('item2', models.IntegerField(default=0, verbose_name='电影id')),
                ('similar', models.FloatField(default=0, verbose_name='相似度')),
            ],
            options={
                'verbose_name': '电影相似度信息',
                'verbose_name_plural': '电影相似度信息',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='评论')),
                ('star', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='星级')),
                ('reviewtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='提交时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.MovieInfo', verbose_name='电影')),
            ],
            options={
                'verbose_name': '用户打分及评论',
                'verbose_name_plural': '用户打分及评论',
            },
        ),
    ]
