# Generated by Django 2.2.6 on 2019-11-12 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRecom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redate', models.DateField(default=datetime.datetime.now, verbose_name='推荐时间')),
            ],
            options={
                'verbose_name': '默认电影推荐',
                'verbose_name_plural': '默认电影推荐',
            },
        ),
    ]
