# Generated by Django 2.2.6 on 2019-11-14 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cinema_Pages', '0002_defaultrecom_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaRecom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0, verbose_name='评分')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.MovieInfo', verbose_name='电影')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户推荐信息',
                'verbose_name_plural': '用户推荐信息',
            },
        ),
    ]
